version: '3.0'

services:
  test:
    image: aiminders/fila:latest
    environment:
      TUSHARE_TOKEN: ${TUSHARE_TOKEN}
    command:
      bash /root/fila/docker-compose.sh
    volumes:
      - .:/root/fila
