version: '3.0'

services:
  bazel:
    image: aiminders/fila:latest
    environment:
      TUSHARE_TOKEN: ${TUSHARE_TOKEN}
    command:
      bash /root/fila/docker-compose.sh
    volumes:
      - .:/root/fila
      - ${BAZEL_USER_ROOT}:/root/cache/bazel
      - ${OUTPUT_DIR}:/root/output
